const { stripe, issueLicenseForSession } = require('./license');

/**
 * Insert a license for every paid checkout session Stripe has ever recorded.
 *
 * Customers who bought before licences were stored have no row in `licenses`,
 * so validation rejects them. This walks Stripe — the only surviving record of
 * those purchases — and mints the missing rows.
 *
 * Everything goes through issueLicenseForSession, which is idempotent on
 * stripe_session_id, so re-running is safe and sessions already issued by the
 * webhook are counted as skipped rather than duplicated.
 *
 * Note the keys minted here are NEW. The key a legacy customer has in their
 * browser was generated by the old code and written down nowhere, so it cannot
 * be recovered; they retrieve this one via /api/recover-license instead.
 */
async function backfillLicenses({ onProgress } = {}) {
  const report = { scanned: 0, paid: 0, issued: 0, skipped: 0, failed: [] };
  const seen = new Set();

  for await (const session of stripe.checkout.sessions.list({ limit: 100 })) {
    report.scanned += 1;

    if (session.payment_status !== 'paid') {
      continue;
    }
    report.paid += 1;

    // Guard against a session appearing twice across page boundaries.
    if (seen.has(session.id)) {
      continue;
    }
    seen.add(session.id);

    try {
      // Ask the database first purely so the report can distinguish a row this
      // run created from one that already existed. Issuance itself is still
      // idempotent, so a race here costs accuracy in the count, nothing more.
      const { getSql } = require('./db');
      const existing = await getSql()`
        SELECT key FROM licenses WHERE stripe_session_id = ${session.id}
      `;

      const key = await issueLicenseForSession(session);

      if (existing.length > 0) {
        report.skipped += 1;
      } else {
        report.issued += 1;
        if (onProgress) {
          onProgress({
            email: session.customer_details?.email || session.customer_email,
            key,
          });
        }
      }
    } catch (error) {
      // A session with no email cannot be issued. Record it and keep going —
      // one bad row must not abandon the rest of the backfill.
      report.failed.push({ session: session.id, reason: error.message });
    }
  }

  return report;
}

module.exports = { backfillLicenses };
